AWSTemplateFormatVersion: "2010-09-09"
Description: What's Done CI group/user
Parameters:
  CiUserName:
    Description: User name for CI
    Type: String
Resources:
  CiUser:
    Type: "AWS::IAM::User"
    Properties:
      Groups:
        - !Ref WhatsDoneCiGroup
      Path: "/"
      UserName: !Ref CiUserName
  WhatsDoneCiGroup:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: whatsdone-ci
      Path: "/"
      Policies:
        - PolicyName: whatsdone-ci-20170716
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: Stmt1489901204000
                Effect: Allow
                Action:
                  - acm:DescribeCertificate
                  - acm:GetCertificate
                  - acm:ListCertificates
                  - acm:ListTagsForCertificate
                  - apigateway:POST
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:UpdateStack
                  - cloudfront:CreateCloudFrontOriginAccessIdentity
                  - iam:GetRole
                  - kms:Decrypt
                  - lambda:CreateFunction
                  - lambda:DeleteFunction
                  - lambda:GetFunctionConfiguration
                  - lambda:UpdateFunctionCode
                  - logs:CreateLogGroup
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
                  - s3:*
                Resource: "*"
