AWSTemplateFormatVersion: "2010-09-09"
Description: What's Done CI group/user
Parameters:
  CiUserName:
    Description: User name for CI
    Type: String
Resources:
  CiUser:
    Type: "AWS::IAM::User"
    Properties:
      Groups:
        - !Ref WhatsDoneCiGroup
      Path: "/"
      UserName: !Ref CiUserName
  WhatsDoneCiGroup:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: whatsdone-ci
      Path: "/"
      Policies:
        - PolicyName: whatsdone-ci-20170716
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: Stmt1489901204000
                Effect: Allow
                Action:
                  - acm:DescribeCertificate
                  - acm:GetCertificate
                  - acm:ListCertificates
                  - acm:ListTagsForCertificate
                  - apigateway:DELETE
                  - apigateway:GET
                  - apigateway:HEAD
                  - apigateway:OPTIONS
                  - apigateway:PATCH
                  - apigateway:POST
                  - apigateway:PUT
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:UpdateStack
                  - cloudfront:CreateCloudFrontOriginAccessIdentity
                  - cloudfront:CreateDistribution
                  - cloudfront:DeleteDistribution
                  - cloudfront:GetDistribution
                  - cloudfront:GetDistributionConfig
                  - cloudfront:UpdateDistribution
                  - dynamodb:CreateTable
                  - dynamodb:DeleteTable
                  - dynamodb:DescribeTable
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:GetRole
                  - iam:DeleteRolePolicy
                  - iam:PassRole
                  - iam:PutRolePolicy
                  - kms:CreateGrant
                  - kms:Encrypt
                  - kms:Decrypt
                  - lambda:AddPermission
                  - lambda:CreateFunction
                  - lambda:DeleteFunction
                  - lambda:GetFunction
                  - lambda:GetFunctionConfiguration
                  - lambda:RemovePermission
                  - lambda:UpdateFunctionCode
                  - lambda:UpdateFunctionConfiguration
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:DeleteLogGroup
                  - logs:DeleteLogStream
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
                  - logs:PutRetentionPolicy
                  - route53:ChangeResourceRecordSets
                  - route53:GetChange
                  - route53:GetHostedZone
                  - s3:*
                Resource: "*"
