const { chromium } = require('playwright');

const sec = sec => sec * 1000;
const wait = msec => new Promise(resolve => setTimeout(resolve, msec));

// The code is originally generated by https://www.npmjs.com/package/playwright-cli
(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();

  const page = await context.newPage();

  await page.goto('https://whatsdone-ci.ryuichi.io/', {waitUntil: 'networkidle'});

  await page.fill('.modal-content.visible-md input[placeholder="Username"]', 'test-e2e');
  await page.fill('.modal-content.visible-md input[placeholder="Password"]', process.env.E2E_USER_PASSWORD);
  await page.click('.modal-content.visible-md input[value="Sign in"]');

  const testText = `test message @ ${new Date().toISOString()}`;
  await page.fill('input[placeholder="What have you done today?"]', testText);
  await page.press('input[placeholder="What have you done today?"]', 'Enter');
  await page.waitForLoadState('networkidle')

  await page.reload({waitUntil: 'networkidle'})
  await page.waitForSelector(`text='${testText}'`)

  await page.hover(`//*[text()[contains(.,'${testText}')]]//ancestor::*[@class='doneitem']`);
  await page.click(`//*[text()[contains(.,'${testText}')]]//ancestor::*[@class='doneitem']/div[3]`);
  await wait(sec(5));  // XXX: waitForLoadState('networkidle') doesn't do the job here

  await page.reload({waitUntil: 'networkidle'})
  const el2 = await page.$(`text='${testText}'`)
  if (el2) throw new Error(`The item "${testText}" should have been successfully deleted.`)

  await page.close();

  await context.close();
  await browser.close();
})();
