name: ryu1kn/whatsdone
on:
  push:
    branches:
    - "**/*"
  pull_request:
concurrency:
#   # This item has no matching transformer
#   maximum_number_of_builds: 1
  group: "${{ github.ref }}"
  cancel-in-progress: true
env:
  AWS_REGION: ap-southeast-2
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.6.0
    - uses: actions/setup-node@v3.8.1
      with:
        cache: npm
        node-version: '18'
    - run: aws configure set s3.signature_version s3v4
    - run: yarn global add kumo
    - run: kumo install
    - run: yarn install
    - run: ./travis-build.sh
      env:
        TRAVIS_COMMIT_RANGE: ${{ github.event.before }}..${{ github.event.after }}
        TRAVIS_BUILD_NUMBER: ${{ github.run_number }}-${{ github.run_id }}
        TRAVIS_BRANCH: ${{ github.ref_name }}
