name: ryu1kn/whatsdone
on:
  push:
    branches:
    - "**/*"
  pull_request:
concurrency:
#   # This item has no matching transformer
#   maximum_number_of_builds: 1
  group: "${{ github.ref }}"
  cancel-in-progress: true
env:
  AWS_REGION: ap-southeast-2
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.6.0
      with:
        fetch-depth: 10
    - uses: actions/setup-node@v3.8.1
      with:
        cache: npm
        node-version: '18'
    - run: ./ci-build.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        BUILD_COMMIT_RANGE: ${{ github.event.before }}...${{ github.event.after }}
        BUILD_NUMBER: ${{ github.run_number }}-${{ github.run_id }}
        BUILD_BRANCH: ${{ github.ref_name }}
